# Generated by Django 4.0.2 on 2022-06-13 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='chunha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenhoap', models.CharField(max_length=300)),
                ('congdung', models.CharField(max_length=600)),
            ],
        ),
    ]
